name: CI Pipeline

# on: [push, pull_request]
on:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Secret Scan
      uses: actions/secret-scan@v1
      with:
        args: 'scan --policy .github/secret-scan-policy.yml'

    - name: Terraform Scan
      uses: hashicorp/terraform-scan-action@v1

    - name: Java Build
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build with Maven
      run: mvn clean install

    - name: Wiz Scan
      uses: bridgecrewio/wiz-scan-action@v1

    - name: Sonar Scan
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        args: '-Dsonar.projectKey=my-project-key'

    - name: Polaris Scan
      uses: polaris-scan/polaris-action@v1

    - name: Blackduck Scan
      uses: blackducksoftware/blackduck-scan-action@v1
      with:
        args: '--upload-source --detect.project.name="MyProject"'

    # Add any additional steps such as deployment or notifications
